version: '3.4'

services:
  knotnpunkt:
    image: dpsgbeckum/knotnpunkt
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - knotnpunkt_data:/data
    environment:
      - "KP_INSTANCE_PATH=/data"

volumes:
  knotnpunkt_data:
