version: '3.4'

services:
  knotnpunkt:
    image: knotnpunkt
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - knotnpunkt_data:/data

volumes:
  knotnpunkt_data:
